### ISSUE TITLE
HIGH  as an intake person I want to be able to add and edit auction Inventory Item sheets online so that I can keep track of all of the items we have

### ISSUE THREAD

**Issue by lavin105** [eliaeiroa/AuctionNow#4]

**Comment by eliaeiroa** [comment]
It includes things like the Auction name to which this item is attached, item name, quantity of the item that will be bid for as a single unit, starting bid price, donor, selling price, condition, and any additional comments.

**Comment by eliaeiroa** [comment]
The form also has a place for indicating approximate size, and storage location, so that we can find the item. We also record if this item is very small (such as a pair of earrings), which for us means that the item has to be stored and displayed with other very small items in a locked case.

**Comment by eliaeiroa** [comment]
be able to add pictures for each item

**Comment by eliaeiroa** [comment]
allows us to provide a preview to potential bidders
